#!/bin/sh -eu

url="https://www.pexels.com/video/852352/download/?fps=30.0&h=360&w=640"
file=paris.mp4
if [ ! -f "$file" ] ; then
  wget "$url" -O $file
fi
ffmpeg -v error -y -i $file -an -r 7.5 -start_number 0 -vf scale="640x360" a_%05d.png
